export { createOxc, experimentalAnalyze, parse, transform } from "./oxc.ts";
export type {
  AnalyzeInput,
  AnalyzeOutput,
  ScopeFact,
  BindingFact,
  BindingKind,
  ReferenceFact,
  ImportFact,
  ExportFact,
  ExportDeclarationKind,
  ExportKind,
  ExportValueKind,
  JsxTagFact,
  Oxc,
  OxcDiagnostic,
  OxcJsxOptions,
  OxcLanguage,
  OxcProgramAst,
  OxcResult,
  OxcSourceLocation,
  OxcSourceSpan,
  OxcSourceType,
  ParseInput,
  ParseOutput,
  SourceMapV3,
  TransformInput,
  TransformOutput,
} from "./types.ts";
